### ISSUE TITLE
Setup instruction in README is wrong

### ISSUE THREAD

**Issue by mkevac** [MarianoGappa/flowbro#28]
What I did?

```
$ go get -u github.com/MarianoGappa/flowbro
$ flowbro 
Flowbro is your bro on localhost:41234!
```

And then went to http://localhost:41234/

I've expected to see something as it is said in README, but I see blank page.

```
INFO[0007] Loading base page failed; ignoring. err=open webroot/configs: no such file or directory
INFO[0013] Loading base page failed; ignoring. err=open webroot/configs: no such file or directory
```

In terminal

**Comment by darron** [comment]
If you do this it should work:

```
git clone git@github.com:marianogappa/flowbro.git
cd flowbro
flowbro
```

Then you should have the files you need to run the demo.

**Comment by marianogappa** [comment]
Thanks for pointing this out. Fixed it with this commit: https://github.com/marianogappa/flowbro/commit/fdcf0f117aa707e1d5319df9ebbc4d0d087d78bb
FYI I also welcome PRs. Cheers!

**Comment by mkevac** [comment]
@darron, yeah, I know. I've pointed out that this wasn't pointed out in README.
Thanks!
